### PR TITLE
allow batch processing of up to 10 messages

### PR DESCRIPTION
**Pull request by akleiber**
We have to replay 300k messages and doing it one by one was just too slow.
This PR adds the `batchSize` option to process up to 10 messages as a batch. 10 is the upper limit of SQS

This  will speed up the replay by up to 10 times.

### CODE REVIEW

**Comment by akleiber** [comment]
@garryyao would be awesome if you would merge this and release a new version.

In the meantime anybody who needs batching feel free to use the cli.js from my fork -> https://github.com/akleiber/replay-aws-dlq/tree/add-batch-option

**Comment by garryyao** [comment]
Happy to have a look if you allow me some time, currently in an urgent project.

**Comment by garryyao** [comment]
Thanks for the batching idea!

**Comment by dnltsk** [comment]
@akleiber recommend using https://github.com/mercury2269/sqsmover - faster processing, bigger community

**Pull request closed without merging**
